name: dart_course_zero_hero
description: Dart course example project for Dart Zero to Hero course.
version: 1.0.0

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  http: ^0.13.6
  path: ^1.8.3
  shared_preferences: ^2.2.1
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.7.0
  test: ^1.23.0
